### ISSUE TITLE
Hyperlinks Issue

### ISSUE THREAD

**Issue by gouthamrajesh** [microsoft/dotnetconf-studentzone#25]
http://aka.ms/dotnetstudentemea
http://aka.ms/dotnetstudentamerica

The links attached above are not working properly. They are hyperlinked in README.md in the "Register for the event" section.
Files are attached for reference :: 

Image 1 ::

![Screenshot_20221104_114316](https://user-images.githubusercontent.com/83950096/199904328-31a3f6ef-eedf-40bc-abbf-8b2784184a01.png)

Image 2 :: 

![Screenshot_20221104_114349](https://user-images.githubusercontent.com/83950096/199904332-a82ba12d-e5de-4513-b67b-2c8b8babc880.png)

**Comment by leestott** [comment]
@gouthamrajesh  thanks for the details both links should be working fine now. Please try again
